# @format

version: '3.8'
# delete this if no database is needed
services:
    # delete this if no database is needed
    app:
        build:
            context: .
            target: dev
        environment:
            - NODE_ENV=development
            - PORT=3000
        ports:
            - ${PORT}:3000
        working_dir: /root/app
        volumes:
            - .:/root/app:chached
        restart: always
        command:
            - /bin/sh
            - -c
            - |
                yarn install
                yarn build
                yarn dev & yarn serve
