# @format

version: '3.8'
services:
    app:
        container_name: ${APP_NAME}
        image: ${APP_NAME}:${APP_TAG}
        restart: always
        environment:
            - PORT=${PORT}
        ports:
            - ${PORT}:3000
